[package]
org = "car_rental"
name = "car_rental_grpc"
version = "0.1.0"
distribution = "2201.12.9"

[build-options]
grpcPath = "proto"

[[dependency]]
org = "ballerina"
name = "grpc"
version = "1.10.0"

[[dependency]]
org = "ballerina"
name = "protobuf"
version = "1.10.0"